// Stable error codes and severity assignments for ACH sentinel errors.
// These are assigned externally to keep the ported error definitions untouched.

import {
  ErrNonAlphanumeric,
  ErrUpperAlpha,
  ErrFieldInclusion,
  ErrConstructor,
  ErrFieldRequired,
  ErrServiceClass,
  ErrSECCode,
  ErrOrigStatusCode,
  ErrAddendaTypeCode,
  ErrTransactionCode,
  ErrIdentificationNumber,
  ErrCardTransactionType,
  ErrValidMonth,
  ErrValidDay,
  ErrValidYear,
  ErrValidState,
  ErrValidISO3166,
  ErrValidISO4217,
  ErrNegativeAmount,
  ErrAddenda98ChangeCode,
  ErrAddenda98RefusedChangeCode,
  ErrAddenda98RefusedTraceSequenceNumber,
  ErrAddenda98CorrectedData,
  ErrAddenda99ReturnCode,
  ErrAddenda99DishonoredReturnCode,
  ErrAddenda99ContestedReturnCode,
  ErrBatchCORAddenda,
  ErrRecordSize,
  ErrBlockingFactor,
  ErrFormatCode,
  ErrExceedsFieldLength,
  ErrForeignExchangeIndicator,
  ErrForeignExchangeReferenceIndicator,
  ErrTransactionTypeCode,
  ErrIDNumberQualifier,
  ErrIATBatchAddendaIndicator,
  ErrOnlyZeros,
  // Batch sentinel errors
  ErrBatchNoEntries,
  ErrBatchADVCount,
  ErrBatchAddendaIndicator,
  ErrBatchOriginatorDNE,
  ErrBatchInvalidCardTransactionType,
  ErrBatchDebitOnly,
  ErrBatchCheckSerialNumber,
  ErrBatchSECType,
  ErrBatchServiceClassCode,
  ErrBatchTransactionCode,
  ErrBatchTransactionCodeAddenda,
  ErrBatchAmountNonZero,
  ErrBatchAmountZero,
  ErrBatchCompanyEntryDescriptionAutoenroll,
  ErrBatchCompanyEntryDescriptionREDEPCHECK,
  ErrBatchAddendaCategory,
  // File sentinel errors
  ErrFileTooLong,
  ErrFileHeader,
  ErrFileControl,
  ErrMisplacedFileHeader,
  ErrExtraRecordsAfterFileControl,
  ErrFileEntryOutsideBatch,
  ErrFileAddendaOutsideBatch,
  ErrFileAddendaOutsideEntry,
  ErrFileBatchControlOutsideBatch,
  ErrFileConsecutiveBatchHeaders,
  ErrFileADVOnly,
  ErrFileIATSEC,
  ErrFileNoBatches,
  ErrInvalidJSON,
} from './errors/index.js';
import type { ACHError } from './errors/index.js';

interface ErrorCodeEntry {
  code: string;
  severity?: 'error' | 'warning' | 'info';
}

/** Map of stable error codes and optional severity overrides for all sentinel errors */
export const errorCodes: Map<ACHError, ErrorCodeEntry> = new Map([
  // Field validation
  [ErrNonAlphanumeric, { code: 'nonAlphanumeric', severity: 'warning' }],
  [ErrUpperAlpha, { code: 'upperAlpha', severity: 'warning' }],
  [ErrFieldInclusion, { code: 'fieldInclusion' }],
  [ErrConstructor, { code: 'constructor' }],
  [ErrFieldRequired, { code: 'fieldRequired' }],
  [ErrServiceClass, { code: 'serviceClass' }],
  [ErrSECCode, { code: 'secCode' }],
  [ErrOrigStatusCode, { code: 'origStatusCode' }],
  [ErrAddendaTypeCode, { code: 'addendaTypeCode' }],
  [ErrTransactionCode, { code: 'transactionCode' }],
  [ErrIdentificationNumber, { code: 'identificationNumber' }],
  [ErrCardTransactionType, { code: 'cardTransactionType' }],
  [ErrValidMonth, { code: 'validMonth' }],
  [ErrValidDay, { code: 'validDay' }],
  [ErrValidYear, { code: 'validYear' }],
  [ErrValidState, { code: 'validState' }],
  [ErrValidISO3166, { code: 'validISO3166' }],
  [ErrValidISO4217, { code: 'validISO4217' }],
  [ErrNegativeAmount, { code: 'negativeAmount' }],
  [ErrAddenda98ChangeCode, { code: 'addenda98ChangeCode' }],
  [ErrAddenda98RefusedChangeCode, { code: 'addenda98RefusedChangeCode' }],
  [ErrAddenda98RefusedTraceSequenceNumber, { code: 'addenda98RefusedTraceSequenceNumber' }],
  [ErrAddenda98CorrectedData, { code: 'addenda98CorrectedData' }],
  [ErrAddenda99ReturnCode, { code: 'addenda99ReturnCode' }],
  [ErrAddenda99DishonoredReturnCode, { code: 'addenda99DishonoredReturnCode' }],
  [ErrAddenda99ContestedReturnCode, { code: 'addenda99ContestedReturnCode' }],
  [ErrBatchCORAddenda, { code: 'batchCORAddenda' }],
  [ErrRecordSize, { code: 'recordSize' }],
  [ErrBlockingFactor, { code: 'blockingFactor' }],
  [ErrFormatCode, { code: 'formatCode' }],
  [ErrExceedsFieldLength, { code: 'exceedsFieldLength' }],
  [ErrForeignExchangeIndicator, { code: 'foreignExchangeIndicator' }],
  [ErrForeignExchangeReferenceIndicator, { code: 'foreignExchangeReferenceIndicator' }],
  [ErrTransactionTypeCode, { code: 'transactionTypeCode' }],
  [ErrIDNumberQualifier, { code: 'idNumberQualifier' }],
  [ErrIATBatchAddendaIndicator, { code: 'iatBatchAddendaIndicator' }],
  [ErrOnlyZeros, { code: 'onlyZeros' }],
  // Batch sentinel errors
  [ErrBatchNoEntries, { code: 'batchNoEntries' }],
  [ErrBatchADVCount, { code: 'batchADVCount' }],
  [ErrBatchAddendaIndicator, { code: 'batchAddendaIndicator' }],
  [ErrBatchOriginatorDNE, { code: 'batchOriginatorDNE' }],
  [ErrBatchInvalidCardTransactionType, { code: 'batchInvalidCardTransactionType' }],
  [ErrBatchDebitOnly, { code: 'batchDebitOnly' }],
  [ErrBatchCheckSerialNumber, { code: 'batchCheckSerialNumber' }],
  [ErrBatchSECType, { code: 'batchSECType' }],
  [ErrBatchServiceClassCode, { code: 'batchServiceClassCode' }],
  [ErrBatchTransactionCode, { code: 'batchTransactionCode' }],
  [ErrBatchTransactionCodeAddenda, { code: 'batchTransactionCodeAddenda' }],
  [ErrBatchAmountNonZero, { code: 'batchAmountNonZero' }],
  [ErrBatchAmountZero, { code: 'batchAmountZero' }],
  [ErrBatchCompanyEntryDescriptionAutoenroll, { code: 'batchCompanyEntryDescriptionAutoenroll' }],
  [ErrBatchCompanyEntryDescriptionREDEPCHECK, { code: 'batchCompanyEntryDescriptionREDEPCHECK' }],
  [ErrBatchAddendaCategory, { code: 'batchAddendaCategory' }],
  // File sentinel errors
  [ErrFileTooLong, { code: 'fileTooLong' }],
  [ErrFileHeader, { code: 'fileHeader' }],
  [ErrFileControl, { code: 'fileControl' }],
  [ErrMisplacedFileHeader, { code: 'misplacedFileHeader' }],
  [ErrExtraRecordsAfterFileControl, { code: 'extraRecordsAfterFileControl' }],
  [ErrFileEntryOutsideBatch, { code: 'fileEntryOutsideBatch' }],
  [ErrFileAddendaOutsideBatch, { code: 'fileAddendaOutsideBatch' }],
  [ErrFileAddendaOutsideEntry, { code: 'fileAddendaOutsideEntry' }],
  [ErrFileBatchControlOutsideBatch, { code: 'fileBatchControlOutsideBatch' }],
  [ErrFileConsecutiveBatchHeaders, { code: 'fileConsecutiveBatchHeaders' }],
  [ErrFileADVOnly, { code: 'fileADVOnly' }],
  [ErrFileIATSEC, { code: 'fileIATSEC' }],
  [ErrFileNoBatches, { code: 'fileNoBatches' }],
  [ErrInvalidJSON, { code: 'invalidJSON' }],
]);
